stores:
  yaml:
    indent: 2
creation_rules:
  - path_regex: secrets.ro.yaml
    azure_keyvault: "https://sops-ro.vault.azure.net/keys/sops-ro-key/"
  - path_regex: src/github/repositories/secrets/*.yaml
    azure_keyvault: "https://sops-master.vault.azure.net/keys/sops-key/"
  - path_regex: secrets.administrator.yaml
    azure_keyvault: "https://sops-administrators.vault.azure.net/keys/sops-administrators-key/"
  - path_regex: .*secret(s)?.*\.yaml
    azure_keyvault: "https://sops-master.vault.azure.net/keys/sops-key/"
