stores:
  yaml:
    indent: 2
creation_rules:
  - path_regex: src/github/repositories/secrets/*.yaml
    azure_keyvault: "https://sops-master.vault.azure.net/keys/sops-key/"
  - path_regex: .*secret(s)?.*\.yaml
    azure_keyvault: "https://sops-master.vault.azure.net/keys/sops-key/"
