import type { AzureGlobalEntraRoleName } from "@/azure/users/entra/const";
import type { AzureGlobalRbacRoleName } from "@/azure/users/rbac/const";

/**
 * __ATTENTION__: Please follow these instructions in order to onboard a new
 * Azure user.
 *
 * 1. Log into Azure at `http://portal.azure.com/`
 * 2. Head to the `Users` resource
 * 3. Click the `New user` button -> `Create new user`
 * 4. Fill out any basic required information
 *   - User Principal Name
 *   - Mail Nickname (sync with User Principal Name)
 *   - First Name
 *   - Last Name
 *   - Display Name (must be `${firstName} ${lastName}`)
 *   - Any other personal information is optional, you may fill it out if you choose
 * 5. SKIP ASSIGNMENTS, they will be done later (Entra roles should not be assigned to new users either).
 * 6. Leave the random password alone (do not forget it / copy it to your clipboard, you must give it to the user; they will be required to change it after logging in)
 * 7. Create
 * 8. Wait for the user to be created
 * 9. THEN, find that `User` resource you just created & copy the `objectId`
 * 10. Add the user to `AZURE_USERS` below
 *   - The key is their firstName + lastName
 *   - Copy all other information you filled out above that the object requires
 *   - Put `objectId` inside `bootstrapObjectId`
 * 11. Create a PR and ask someone from `@Patina-Network/infra` to review & merge the changes.
 *   - View the Pulumi diff inside the PR; it will indicate what accesses the user will receive once merged.
 * 12. Wait for the changes to be merged and successfully reconciled by Pulumi (check CICD inside the latest tag generated by your PR)
 * 13. Once step 12 is complete, come back
 *     here and set the `bootstrapObjectId`. Pulumi can manage this state without it & it is safe to remove.
 * 13. Follow step 11 and 12
 */

type AzureUser = {
  /** Set this to objectId if you are importing a user into Pulumi. Then once state is reconciled, delete it. */
  bootstrapObjectId?: string;
  /** Roles giving permission for Microsoft Entra, which manages access to Microsoft's suite of apps, but not Azure.  */
  entraRoles: readonly AzureGlobalEntraRoleName[];
  /** Roles giving permission for Azure, allowing developers to view and manage resources.  */
  azureRoles: readonly AzureGlobalRbacRoleName[];
  /** The SMTP address for the user. This property cannot be unset once specified.  */
  mail: string;
  /** The mail alias for the user. Defaults to the user name part of the user principal name (UPN).  */
  mailNickname: string;
  /** The user principal name (UPN) of the user.  */
  userPrincipalName: string;
};

type AzureUserFullName = string;

// New users should be created in Azure, then bootstrapped to this repository.
// Then, we can use Pulumi to wire up resources & permissions.
export const AZURE_USERS = {
  "Henry Chen": {
    bootstrapObjectId: undefined,
    entraRoles: ["globalAdministrator"],
    azureRoles: ["owner"],
    mail: "henry@patinanetwork.onmicrosoft.com",
    mailNickname: "henry",
    userPrincipalName: "henry@patinanetwork.onmicrosoft.com",
  },
  "Tahmid Ahmed": {
    bootstrapObjectId: undefined,
    entraRoles: ["globalAdministrator", "userAdministrator"],
    azureRoles: ["owner"],
    mail: "tahmid@patinanetwork.onmicrosoft.com",
    mailNickname: "tahmid",
    userPrincipalName: "tahmid@patinanetwork.onmicrosoft.com",
  },
  "Kevin Ma": {
    bootstrapObjectId: undefined,
    entraRoles: ["globalAdministrator", "userAdministrator", "globalReader"],
    azureRoles: ["contributor"],
    mail: "kevin.ma@patinanetwork.onmicrosoft.com",
    mailNickname: "kevin.ma",
    userPrincipalName: "kevin.ma@patinanetwork.onmicrosoft.com",
  },
  "Ray Zhou": {
    bootstrapObjectId: undefined,
    entraRoles: ["userAdministrator", "globalReader"],
    azureRoles: ["contributor"],
    mail: "ray@patinanetwork.onmicrosoft.com",
    mailNickname: "ray",
    userPrincipalName: "ray@patinanetwork.onmicrosoft.com",
  },
  "Arshadul Monir": {
    bootstrapObjectId: undefined,
    entraRoles: ["globalReader", "userAdministrator"],
    azureRoles: ["contributor"],
    mail: "arshadul@patinanetwork.onmicrosoft.com",
    mailNickname: "arshadul",
    userPrincipalName: "arshadul@patinanetwork.onmicrosoft.com",
  },
  "Haoking Luo": {
    bootstrapObjectId: undefined,
    entraRoles: ["globalReader", "userAdministrator"],
    azureRoles: ["reader"],
    mail: "haoking.luo@patinanetwork.onmicrosoft.com",
    mailNickname: "haoking.luo",
    userPrincipalName: "haoking.luo@patinanetwork.onmicrosoft.com",
  },
  "Randy Dean": {
    bootstrapObjectId: undefined,
    entraRoles: ["globalReader", "userAdministrator"],
    azureRoles: ["reader"],
    mail: "randy.dean@patinanetwork.onmicrosoft.com",
    mailNickname: "randy.dean",
    userPrincipalName: "randy.dean@patinanetwork.onmicrosoft.com",
  },
  "Isabella Lam": {
    bootstrapObjectId: undefined,
    entraRoles: ["globalReader", "userAdministrator"],
    azureRoles: ["reader"],
    mail: "isabella.lam@patinanetwork.onmicrosoft.com",
    mailNickname: "isabella.lam",
    userPrincipalName: "isabella.lam@patinanetwork.onmicrosoft.com",
  },
  "Allison Lee": {
    bootstrapObjectId: undefined,
    entraRoles: ["globalReader", "userAdministrator"],
    azureRoles: ["reader"],
    mail: "allison.lee@patinanetwork.onmicrosoft.com",
    mailNickname: "allison.lee",
    userPrincipalName: "allison.lee@patinanetwork.onmicrosoft.com",
  },
  "Andrew Yu": {
    bootstrapObjectId: undefined,
    entraRoles: ["globalReader", "userAdministrator"],
    azureRoles: ["reader"],
    mail: "andrew.yu@patinanetwork.onmicrosoft.com",
    mailNickname: "andrew.yu",
    userPrincipalName: "andrew.yu@patinanetwork.onmicrosoft.com",
  },
  "Maliha Tasnim": {
    bootstrapObjectId: undefined,
    entraRoles: ["globalReader", "userAdministrator"],
    azureRoles: ["reader"],
    mail: "maliha.tasnim@patinanetwork.onmicrosoft.com",
    mailNickname: "maliha.tasnim",
    userPrincipalName: "maliha.tasnim@patinanetwork.onmicrosoft.com",
  },
  "Ousmane Barrie": {
    bootstrapObjectId: undefined,
    entraRoles: ["globalReader", "userAdministrator"],
    azureRoles: ["contributor"],
    mail: "ousmane.barrie@patinanetwork.onmicrosoft.com",
    mailNickname: "ousmane.barrie",
    userPrincipalName: "ousmane.barrie@patinanetwork.onmicrosoft.com",
  },
} as const satisfies Record<AzureUserFullName, AzureUser>;

export type AzureUserName = keyof typeof AZURE_USERS;
